<?php
/*
 *  ring bat phone using BT Mojo:
 *  	http://mojo.bt.com
 *
 *  Mojo is a Web friendly exposure of BT's Web21C SDK:
 *  	http://web21c.bt.com
 *
 *  Form parameters:
 *    - username should be WikiFormatName
 *    - telno should be caller's international format telephone number +4479... 31283... etc
 *
 */

    /*
     *  pull in a secret PHP file with:
     *
     *   the registered gadgetKey:
     *   $mojoGadgetKey="90ff2e7993c986eee44626122f22f199bb52b1b7";
     *
     *   your mojo username:
     *   $mojoUsername = "osmosoft";
     *
     *   the secret generated by authorizing the gadget for your username:
     *   $mojoGadgetSecret="591400d1dfdsafdsafdsfsd...";
     *
     *   the telephone number of your bat phone:
     *   $callee="+4479...";
     */
    require_once("conf/mojoBatphoneKeys.php");

    /*
     *  missing username and telno?
     *  - put up a HTML form
     */
    if (!isset($_POST['username']) || !isset($_POST['telno'])) {
?><html>
<body>
<h3>Ring the Bat Phone</h3>

    <form method="POST" action="<?php echo $_SERVER['REQUEST_URI']  ?>">
        <label for="username">username:</label>
        <input type="text" id="username" name="username" value="" />
        <br/>
        <label for="telno">telno:</label>
        <input type="text" id="telno" name="telno" value="" />
	<br/>
	<input type='submit' value='Submit'/>
   </form>

</body>
</html>
<?php 
	exit(0);
}



	/*
	 *  make phone call using Mojo!
	 */
        $username = $_POST['username'];
        $telno = $_POST['telno'];

	/*
         *  generate unique name for call:
         */
	$mojoCallName = $username . "-" . time();
	$digest = sha1("$mojoUsername:$mojoGadgetKey:$mojoCallName:$mojoGadgetSecret");

	$params =
	   "name=".urlencode($mojoCallName) ."&".
	   "caller=".urlencode($telno) ."&".
	   "callee=".urlencode($mojoBatphone) ."&".
	   "gadgetkey=".urlencode($mojoGadgetKey) ."&".
	   "username=".urlencode($mojoUsername) ."&" .
	   "digest=".urlencode($digest);

	$post = curl_init("http://mojo.bt.com/calls.xml");
	curl_setopt($post, CURLOPT_HEADER, 0);
	curl_setopt($post, CURLOPT_POST, 1);
	curl_setopt($post, CURLOPT_POSTFIELDS, $params);
	curl_exec($post);
	curl_close($post);

	exit(0);

?>
