# Simple Makefile for some common tasks. This will get
# fleshed out with time to make things easier on developer
# and tester types.
.PHONY: clean test dist release pypi

clean:
	rm tinytiddly.tar || true
	rm tinytiddlywiki.html || true
	rm -r tinytiddly || true
	rm tiddlywiki_standalone.html || true
	rm -rf temp