var nameToUNStandard ={
'PALESTINE': "PALESTINIAN TERRITORY, OCCUPIED",
'CONGO': "Democratic Republic of the Congo",
'RUSSIA':"RUSSIAN FEDERATION",
'UNITED REPUBLIC OF TANZANIA': "TANZANIA, UNITED REPUBLIC OF",
"THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA":"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
"UNTIED ARAB EMIRATES":"UNITED ARAB EMIRATES",
"TAIWAN": "TAIWAN, PROVINCE OF CHINA",
"COTE D'IVOIRE":"CÔTE D'IVOIRE",
"BURMA": "MYNAMAR",
"DEMOCRATIC REPUBLIC OF THE CONGO":"CONGO, THE DEMOCRATIC REPUBLIC OF THE",


"BRITISH VIRGIN ISLANDS":"VIRGIN ISLANDS, BRITISH",
"SOUTH GEORGIA SOUTH SANDWICH ISLANDS" :"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
"FRENCH SOUTHERN AND ANTARCTIC LANDS":"FRENCH SOUTHERN TERRITORIES",//check
"HOLY SEE (VATICAN CITY)":"HOLY SEE (VATICAN CITY STATE)",
"IRAN (ISLAMIC REPUBLIC OF)":"IRAN, ISLAMIC REPUBLIC OF",
"MACAU":"MACAO",
"REPUBLIC OF MOLDOVA":"MOLDOVA, REPUBLIC OF",
"PITCAIRN ISLANDS":"PITCAIRN",
"REUNION":"RÉUNION",
"SAINT BARTHELEMY":"SAINT BARTHÉLEMY",
"SVALBARD":"SVALBARD AND JAN MAYEN",
"UNITED STATES VIRGIN ISLANDS":"VIRGIN ISLANDS, U.S.",
"WALLIS AND FUTUNA ISLANDS":"WALLIS AND FUTUNA"
};
