// countriesWhereIllegal object created using the code in convertSourceCountries.js
var countriesWhereIllegal = {
	"AFGHANISTAN":"Afghanistan",
	"ALGERIA":"Algeria",
	"AFGHANISTAN":"Afghanistan",
	"ALGERIA":"Algeria",
	"ANGOLA":"Angola",
	"ANTIGUA AND BARBUDA":"Antigua & Barbuda",
	"BAHRAIN":"Bahrain",
	"BANGLADESH":"Bangladesh",
	"BARBADOS":"Barbados",
	"BELIZE":"Belize",
	"BENIN":"Benin",
	"BHUTAN":"Bhutan",
	"BOTSWANA":"Botswana",
	"BRUNEI DARUSSALAM":"Brunei",
	"CAMEROON":"Cameroon",
	"COMOROS":"Comoros",
	"COOK ISLANDS":"Cook Islands (New Zealand associate)",
	"DJIBOUTI":"Djibouti",
	"DOMINICA":"Dominica",
	"ERITREA":"Eritrea",
	"ETHIOPIA":"Ethiopia",
	"GAMBIA":"Gambia",
	"PALESTINIAN TERRITORY, OCCUPIED":"Gaza (Palestinian authority)",
	"GHANA":"Ghana",
	"GRENADA":"Grenada",
	"GUINEA":"Guinea",
	"GUINEA-BISSAU":"Guinea-Bissau",
	"GUYANA":"Guyana",
	"INDIA":"India",
	"IRAN, ISLAMIC REPUBLIC OF":"Iran",
	"JAMAICA":"Jamaica",
	"KENYA":"Kenya",
	"KIRIBATI":"Kiribati",
	"KUWAIT":"Kuwait",
	"LEBANON":"Lebanon",
	"LESOTHO":"Lesotho",
	"LIBERIA":"Liberia",
	"LIBYAN ARAB JAMAHIRIYA":"Libya",
	"MALAWI":"Malawi",
	"MALAYSIA":"Malaysia",
	"MALDIVES":"Maldives",
	"MAURITANIA":"Mauritania",
	"MAURITIUS":"Mauritius",
	"MOROCCO":"Morocco",
	"MOZAMBIQUE":"Mozambique",
	"MYANMAR":"Myanmar/Burma",
	"NAMIBIA":"Namibia",
	"NAURU":"Nauru",
	"NEPAL":"Nepal",
	"NIGERIA":"Nigeria",
	"NIUE":"Niue (New Zealand associate)",
	"OMAN":"Oman",
	"PAKISTAN":"Pakistan",
	"PALAU":"Palau",
	"PANAMA":"Panama",
	"PAPUA NEW GUINEA":"Papua New Guinea",
	"QATAR":"Qatar",
	"SAUDI ARABIA":"Saudi-Arabia",
	"SENEGAL":"Senegal",
	"SEYCHELLES":"Seychelles",
	"SIERRA LEONE":"Sierra Leone",
	"SINGAPORE":"Singapore",
	"SOLOMON ISLANDS":"Solomon Islands",
	"SOMALIA":"Somalia",
	"SRI LANKA":"Sri Lanka",
	"SAINT KITTS AND NEVIS":"St Kitts & Nevis",
	"SAINT LUCIA":"St Lucia",
	"SAINT VINCENT AND THE GRENADINES":"St Vincent & the Gren.",
	"SUDAN":"Sudan",
	"SWAZILAND":"Swaziland",
	"SYRIAN ARAB REPUBLIC":"Syria",
	"SAO TOME AND PRINCIPE":"São Tomé & Princ.",
	"TANZANIA, UNITED REPUBLIC OF":"Tanzania",
	"TOGO":"Togo",
	"TOKELAU":"Tokelau (New Zealand associate)",
	"TONGA":"Tonga",
	"TRINIDAD AND TOBAGO":"Trinidad & Tobago",
	"TUNISIA":"Tunisia",
	"CYPRUS":"Turkish Republic of Northern Cyprus",
	"TURKMENISTAN":"Turkmenistan",
	"TUVALU":"Tuvalu",
	"UNITED ARAB EMIRATES":"U. Arab Emirates",
	"UGANDA":"Uganda",
	"UZBEKISTAN":"Uzbekistan",
	"SAMOA":"Western Samoa",
	"YEMEN":"Yemen",
	"ZAMBIA":"Zambia",
	"ZIMBABWE":"Zimbabwe"
};

// This list is the countries from the section headed: "Homosexual acts illegal"
var sourceCountries = [
	"Afghanistan",
	"Algeria",
	"Angola",
	"Antigua & Barbuda",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belize",
	"Benin",
	"Bhutan",
	"Botswana",
	"Brunei",
	"Cameroon",
	"Comoros",
	"Cook Islands (New Zealand associate)",
	"Djibouti",
	"Dominica",
	"Eritrea",
	"Ethiopia",
	"Gambia",
	"Gaza (Palestinian authority)",
	"Ghana",
	"Grenada",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"India",
	"Iran",
	"Jamaica",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mauritania",
	"Mauritius",
	"Morocco",
	"Mozambique",
	"Myanmar/Burma",
	"Namibia",
	"Nauru",
	"Nepal",
	"Nigeria",
	"Niue (New Zealand associate)",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Qatar",
	"St Kitts & Nevis",
	"St Lucia",
	"St Vincent & the Gren.",
	"São Tomé & Princ.",
	"Saudi-Arabia",
	"Senegal",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Solomon Islands",
	"Somalia",
	"Sri Lanka",
	"Sudan",
	"Swaziland",
	"Syria",
	"Tanzania",
	"Togo",
	"Tokelau (New Zealand associate)",
	"Tonga",
	"Trinidad & Tobago",
	"Tunisia",
	"Turkish Republic of Northern Cyprus",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"U. Arab Emirates",
	"Uzbekistan",
	"Western Samoa",
	"Yemen",
	"Zambia",
	"Zimbabwe"
];
