
// This list is the countries from the section headed: "Homosexual acts legal (The year in brackets refers to the year when the reform came into force)"
var countriesWhereLegal = {
			"ALBANIA":"Albania",
			"ANDORRA":"Andorra",
			"ARGENTINA":"Argentina",
			"ARMENIA":"Armenia",
			"AUSTRALIA":"Australia",
			"AUSTRIA":"Austria",
			"AZERBAIJAN":"Azerbaijan",
			"BAHAMAS":"Bahamas",
			"BELARUS":"Belarus",
			"BELGIUM":"Belgium",
			"BOLIVIA":"Bolivia",
			"BOSNIA AND HERZEGOVINA":"Bosnia-Herz.",
			"BRAZIL":"Brazil",
			"BULGARIA":"Bulgaria",
			"BURUNDI":"Burundi",
			"CAMBODIA":"Cambodia",
			"CANADA":"Canada",
			"CAPE VERDE":"Cape Verde",
			"CENTRAL AFRICAN REPUBLIC":"Central African Rep.",
			"CHILE":"Chile",
			"CHINA":"China",
			"COLOMBIA":"Colombia",
			"CONGO":"Congo",
			"CROATIA":"Croatia",
			"CUBA":"Cuba",
			"CYPRUS":"Cyprus",
			"CZECH REPUBLIC":"Czech Republic",
			"CÔTE D'IVOIRE":"Côte d’Ivoire",
			"DENMARK":"Denmark",
			"DOMINICAN REPUBLIC":"Dominican Rep.",
			"ECUADOR":"Ecuador",
			"EL SALVADOR":"El Salvador",
			"EQUATORIAL GUINEA":"Equatorial-Guinea",
			"ESTONIA":"Estonia",
			"FIJI":"Fiji",
			"FINLAND":"Finland",
			"FRANCE":"France",
			"GABON":"Gabon",
			"GEORGIA":"Georgia",
			"GERMANY":"Germany",
			"GREECE":"Greece",
			"GUATEMALA":"Guatemala",
			"HAITI":"Haiti",
			"HONDURAS":"Honduras",
			"HUNGARY":"Hungary",
			"ICELAND":"Iceland",
			"IRELAND":"Ireland",
			"ISRAEL":"Israel",
			"ITALY":"Italy",
			"JAPAN":"Japan",
			"JORDAN":"Jordan",
			"KAZAKHSTAN":"Kazakhstan",
			//"unknown":"Kosovo",
			"KYRGYZSTAN":"Kyrgyzstan",
			"LAO PEOPLE'S DEMOCRATIC REPUBLIC":"Laos",
			"LATVIA":"Latvia",
			"LIECHTENSTEIN":"Liechtenstein",
			"LITHUANIA":"Lithuania",
			"LUXEMBOURG":"Luxembourg",
			"MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF":"Macedonia",
			"MADAGASCAR":"Madagascar",
			"MALI":"Mali",
			"MALTA":"Malta",
			"MARSHALL ISLANDS":"Marshall Islands",
			"MEXICO":"Mexico",
			"MICRONESIA, FEDERATED STATES OF":"Micronesia",
			"MOLDOVA, REPUBLIC OF":"Moldova",
			"MONACO":"Monaco",
			"MONGOLIA":"Mongolia",
			"MONTENEGRO":"Montenegro",
			"NETHERLANDS":"Netherlands",
			"NETHERLANDS ANTILLES":"Netherlands Antilles",
			"NEW ZEALAND":"New Zealand",
			"NICARAGUA":"Nicaragua",
			"KOREA, REPUBLIC OF":"North Korea",
			"NORWAY":"Norway",
			"PARAGUAY":"Paraguay",
			"PERU":"Peru",
			"PHILIPPINES":"Philippines",
			"POLAND":"Poland",
			"PORTUGAL":"Portugal",
			"PUERTO RICO":"Puerto Rico (US associate)",
			"ROMANIA":"Romania",
			"RUSSIAN FEDERATION":"Russia",
			"RWANDA":"Rwanda",
			"SAN MARINO":"San Marino",
			"SERBIA":"Serbia",
			"SLOVAKIA":"Slovakia",
			"SLOVENIA":"Slovenia",
			"SOUTH AFRICA":"South Africa",
			"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF":"South Korea",
			"SPAIN":"Spain",
			"SURINAME":"Suriname",
			"SWEDEN":"Sweden",
			"SWITZERLAND":"Switzerland",
			"TAIWAN, PROVINCE OF CHINA":"Taiwan",
			"TAJIKISTAN":"Tajikistan",
			"THAILAND":"Thailand",
			"TIMOR-LESTE":"Timor-Leste",
			"TURKEY":"Turkey",
			"UNITED KINGDOM":"U. Kingdom",
			"UKRAINE":"Ukraine",
			"UNITED STATES":"United States",
			"URUGUAY":"Uruguay",
			"VANUATU":"Vanuatu",
			"VENEZUELA":"Venezuela",
			"VIET NAM":"Vietnam",
			"PALESTINIAN TERRITORY, OCCUPIED":"West Bank (Palestinian authority)"
		};