pref("tiddlysnip.wikiuser","UserName");
pref("tiddlysnip.tiddlertags","TiddlySnip");
pref("tiddlysnip.enablebackups",true);
pref("tiddlysnip.togglebackuppath",false);
pref("tiddlysnip.backuppath","");
pref("tiddlysnip.includesourceinfo",true);
pref("tiddlysnip.showtwaftersave",false);
pref("tiddlysnip.tabchoice","3");
pref("tiddlysnip.categories","default.ITEM..NEXT.code.ITEM.JS code TiddlySnip.NEXT.japanese.ITEM.language study japanese.NEXT.bookmark.ITEM.boomark");
pref("tiddlysnip.enablecategories",false);
pref("tiddlysnip.enableclipboard",false);
pref("tiddlysnip.enablebookmark",false);
pref("tiddlysnip.uploadstoreurl","");
pref("tiddlysnip.uploaddir",".");
pref("tiddlysnip.uploadbackupdir",".");
pref("tiddlysnip.uploadusername","");
pref("tiddlysnip.uploadfilename","");