#!/usr/bin/env bash

# Usage:
#  uploadalpha [cleanup]

# default values
USERNAME=${2:-$LOGNAME}
HOST="$USERNAME@tiddlywiki.com"
DIR="/var/www/www.tiddlywiki.com/htdocs"
OWNER="www-data:www-data"
PERM="664"

# setPermissions()
# Usage:
#  setPermissions file
function setPermissions() {
	COMMANDS="$COMMANDS sudo chown $OWNER $1;"
	COMMANDS="$COMMANDS sudo chmod $PERM $1;"
}

# upload files to temporary folder
echo
echo "uploading files"
echo
FILES="empty.html TiddlySaver.jar"
scp $FILES "$HOST:./tmp/"

# transfer files to their respective folders
echo
echo "transferring files"
echo
COMMANDS="ssh $HOST"
# Empty
COMMANDS="$COMMANDS sudo cp ./tmp/empty.html $DIR/alpha/empty.html;"
setPermissions "$DIR/alpha/empty.html"
# TiddlySaver
COMMANDS="$COMMANDS sudo mv ./tmp/TiddlySaver.jar $DIR/alpha/TiddlySaver.jar;"
setPermissions "$DIR/alpha/TiddlySaver.jar"
# execute
$COMMANDS

# cleanup
if [ "$2" = "true" ]; then
	echo "cleaning up (removing cooked files)"
	echo "removing empty.html"
	rm "empty.html"
	echo "removing TiddlySaver.jar"
	rm "TiddlySaver.jar"
fi
