#!/usr/bin/env sh

# report core commits to [twdev]

sender="svn@tiddlywiki.org"
recipient=${3:-"TiddlyWikiDev@googlegroups.com"}

repo="$1"
rev="$2"

match=`svnlook dirs-changed -r $rev $repo | grep Trunk/core`
if [ "$match" ]; then
	url="http://trac.tiddlywiki.org/changeset/$rev"
	msg=`svnlook log -r $rev $repo | head -n1`
	info=`svnlook info -r $rev $repo`
	changed=`svnlook changed -r $rev $repo`
	diff=`svnlook diff -r $rev --no-diff-deleted $repo`
	/usr/sbin/sendmail "$recipient" <<EOF
From: $sender
Subject: [commit #$rev] $msg

$url

$info

---------------

$changed

---------------

$diff
EOF
fi
