# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter-PhpWiki
version:      0.51
version_from: lib/HTML/WikiConverter/PhpWiki.pm
installdirs:  site
requires:
    HTML::WikiConverter:           0.52
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
