<?php

    /*
     *   the registered gadgetKey
     */
    $mojoGadgetKey="90ff2e7993c986eee44626122f22f199bb52b1b7";

    /*
     *  your mojo username
     */
    $mojoUsername = "osmosoft";

    /*
     *  the secret generated by authorizing the gadget for your username
     */
    $mojoGadgetSecret = "591400d1b000bc3a0af7894705fc41a867f1187e";

    /*
     *  telephone number of your bat phone
     *  - international format:
     */
    $mojoBatphone = "+447918880881";

?>
