#!/usr/bin/env bash

# Usage:
#  bld [release]

DEFAULT_RELEASE="2.5.3"
RELEASE=${1:-$DEFAULT_RELEASE}
DEST=$PWD/../../../cooked/tiddlywiki.com
mkdir -p $PWD/../../../cooked
mkdir -p $PWD/../../../cooked/tiddlywiki.com
RECIPE=$PWD/recipes/index.$RELEASE.html.recipe
ruby -Ku -C ../../tools/cooker cook.rb $RECIPE -d$DEST -q $2 $3 $4 $5
RECIPE=$PWD/recipes/empty.$RELEASE.html.recipe
ruby -Ku -C ../../tools/cooker cook.rb $RECIPE -d$DEST -q $2 $3 $4 $5
cp $DEST/empty.$RELEASE.html /tmp/empty.html
rm $DEST/empty.$RELEASE.zip
zip -j $DEST/empty.$RELEASE.zip /tmp/empty.html $DEST/TiddlySaver.jar
rm /tmp/empty.html
