#!/bin/bash
DEFAULT_RELEASE=2.5.1.B1
RELEASE=${1:-$DEFAULT_RELEASE}
DEST=$PWD
RECIPE=$PWD/recipes/index.$RELEASE.html.recipe
ruby -Ku -C ../../tools/cooker cook.rb $RECIPE -d$DEST -q $2 $3 $4 $5
RECIPE=$PWD/recipes/empty.$RELEASE.html.recipe
ruby -Ku -C ../../tools/cooker cook.rb $RECIPE -d$DEST -q $2 $3 $4 $5
