#!/bin/bash
#
# Usage:
#  uploadbeta [release] [cleanup]

# default values
DEFAULT_RELEASE="2.4.0.B2"
RELEASE=${1:-$DEFAULT_RELEASE}
HOST="tiddlywiki.com"
DIR="/var/www/www.tiddlywiki.com/htdocs"
OWNER="www-data:www-data"
PERM="664"

# setPermissions()
# Usage:
#  setPermissions file
function setPermissions() {
	COMMANDS="$COMMANDS sudo chown $OWNER $1;"
	COMMANDS="$COMMANDS sudo chmod $PERM $1;"
}

# upload files to temporary folder
echo
echo "uploading files"
echo
FILES="index.$RELEASE.html empty.$RELEASE.html"
scp $FILES "$HOST:./tmp/"

# transfer files to their respective folders
echo
echo "transferring files"
echo
COMMANDS="ssh $HOST"
# Index
COMMANDS="$COMMANDS sudo mv ./tmp/index.$RELEASE.html $DIR/beta/index.html;"
setPermissions "$DIR/beta/index.html"
# Empty
COMMANDS="$COMMANDS sudo cp ./tmp/empty.$RELEASE.html $DIR/beta/empty.html;"
setPermissions "$DIR/beta/empty.html"
# Upgrade
COMMANDS="$COMMANDS sudo mv ./tmp/empty.$RELEASE.html $DIR/upgrade/index.html;"
setPermissions "$DIR/upgrade/index.html"
# TiddlySaver
COMMANDS="$COMMANDS sudo mv ./tmp/TiddlySaver.html $DIR/beta/TiddlySaver.jar;"
setPermissions "$DIR/beta/TiddlySaver.jar"
# execute
$COMMANDS

# cleanup
if [ "$2" = "true" ]; then
	echo "cleaning up (removing cooked files)"
	echo "removing index.$RELEASE.html"
	rm "index.$RELEASE.html"
	echo "removing empty.$RELEASE.html"
	rm "empty.$RELEASE.html"
	echo "removing TiddlySaver.jar"
	rm "TiddlySaver.jar"
fi
