#!/bin/sh
cd ../static/lib
cat \
jquery-1.3.2.min.js \
ISO-3166.js \
app.js \
dragtable.js \
dataTables-1.5/media/js/jquery.dataTables.js \
FixedHeader.js \
records.js \
GoogleMaps.js \
GoogleAnalytics.js \
> agg.js
cp ../js/agg.js ../js/agg_backup.js
mv agg.js ../js/agg.js
rm ../js/agg_backup.js